import { Providers } from './Providers';
import Header from './Header';
import Navbar from './Navbar';
import './default.css';
import { Suspense } from 'react';
import { Analytics } from '@vercel/analytics/react';
export const metadata = {
    title: 'React Docs',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <body>
                <Providers>
                    <Header />
                    <Navbar />
                    <div className='pl-72 p-4 h-full min-h-full min-h-screen'>
                        <Suspense fallback={<p>loading...</p>}>
                            {children}
                        </Suspense>
                    </div>
                </Providers>
                <Analytics />
            </body>
        </html>
    );
}
